# lattice information
cell parameters: [103.45,50.28,69.380,90.00,109.67,90.00]  # in A and degree

# reference generation parameters
resolution cutoff: 4.5  #  highest resolution for reference, in A
lattice type: "monoclinic"  # support monoclinic, orthorhombic
centering: "C"  # centering type, optional, support I, A, B, C, P

# indexing parameters
sort by: "snr"  # peak list sort method, support snr, intensity
seed pool size: 5  # generate seed from this pool. 5 is good for SFX
refine cycles: 10  # refine indexing solution
refine mode: "global"
seed length tolerance: 0.003  # in A^-1, depends on sample and exp. setup
seed hkl tolerance: 0.2  # seed hkl tolerence
centering factor: 0.2  # centering weighting factor
eval tolerance: 0.25  # pair peak criterion
multi index: False  # try to index multiple crystal for single pattern?
top solutions: 5
miller set: null
# first event: 0  # first event for indeixng, optional
# last event: 100  # last event for indexing, optional

hkl constraint: False  # if apply strict hkl constraint, users must specify a hkl file.
# hkl file: "sample.hkl"  # txt file including all possiable miller indices, optional
#
verbose: True
number of try: 30
number of failed try: 5
